config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'

	resources :sessions
	match '/signout', to: 'sessions#destroy', via: :delete

	resources :users
	match '/users_password_reset', to: 'users#password_reset', via: :get
	match '/users_password_reset_update', to: 'users#password_reset_update', via: :put

	resources :categories
	match '/categoriesbulkinput', to: 'categories#bulkinput', via: :get
	match '/categoriesbulkinputupdate', to: 'categories#bulkinputupdate', via: :get

	resources :whats
	match '/whats_remap', to: 'whats#remap', via: :get
	match '/whats_remapupdate', to: 'whats#remapupdate', via: :put

	resources :what_maps

	resources :accountmaps

	resources :items

	resources :bulkinput

	resources :yearbudget

	resources :runningbudget

	resources :donations

	resources :rentalcosts

	resources :rent

	resources :transfers

	resources :unused

	resources :taxes

	resources :accounts
	match 'account_close', to: 'accounts#close', via: :put

	resources :investments

	resources :investmentbulkinput

	resources :summary_types
	match '/summary_types_showupdate', to: 'summary_types#showupdate', via: :put

	resources :summary

	resources :charts

	resources :rebalance

	resources :rebalance_types
	match '/rebalance_types_showupdate', to: 'rebalance_types#showupdate', via: :put

	match '/admin_roles', to: 'admin#roles', via: :get
	match '/admin_roles_edit', to: 'admin#roles_edit', via: :get
	match '/admin_roles_update', to: 'admin#roles_update', via: :get
	match '/admin_schema', to: 'admin#schema', via: :get
	match '/admin_datacheck', to: 'admin#datacheck', via: :get

end

app/models/what.rb
class What < ApplicationRecord
	
	belongs_to :category
	has_many :items
	has_many :what_maps

end

app/controllers/whats_controller.rb
class WhatsController < ApplicationController

	before_action :require_signed_in
	before_action :require_expenses

	def index
		@title = 'What To Category Map'
		@whats = What.joins(:category).all.order('ctype, category, subcategory, what')
		@categorymap = Hash.new
		Category.all.each do |category|
			@categorymap[category.id] = Hash.new
			@categorymap[category.id]['ctype'] = category.ctype
			@categorymap[category.id]['category'] = category.category
			@categorymap[category.id]['subcategory'] = category.subcategory
			@categorymap[category.id]['tax'] = category.tax
		end
	end

	def new
		@title = 'New What Map'
		@what = What.new
		@categories = Category.all.order('ctype, category, subcategory, tax')
	end

	def create
		@what = What.new(what_params)
		if @what.save
			redirect_to whats_path, notice: 'What Map Added'
		else
			redirect_to whats_path, alert: 'Failed to create What Map'
		end
	end

	def edit
		@title = 'Edit What Map'
		@what = What.find(params[:id])
		@categories = Category.all.order('ctype, category, subcategory, tax')
	end

	def update
		@what = What.find(params[:id])
		if @what.update(what_params)
			redirect_to whats_path, notice: 'What map Updated'
		else
			redirect_to whats_path, alert: 'Failed to create What map'
		end
	end

	def show
		@what = What.find(params[:id])
		@title = "Where is '#{@what.what}'"
		@items = Item.where("what_id = ?", @what.id).order('date')
	end

	def remap
		@title = 'Remap specified What to another what'
		@what = What.find(params[:id])
		@whats = [['', 0]]
		What.where("id != ?", @what.id).order('what').each do |what|
			@whats.push([what.what, what.id])
		end
	end

	def remapupdate
		@id = params[:id]
		@what = What.find(@id)
		@newid = params[:newid]
		@newwhat = What.find(@newid)
		# update WhatMaps
		WhatMap.where("what_id = ?", @id).update_all(what_id: @newid)
		count = Item.where("what_id = ?", @id).count
		# update Items
		Item.where("what_id = ?", @id).update_all(what_id: @newid)
		What.find(@id).delete
		redirect_to whats_path, notice: "#{count} '#{@what.what}' remapped to '#{@newwhat.what}'"
	end

	def destroy
		@what = What.find(params[:id])
		if Item.where("what_id = ?", @what.id).count > 0
			redirect_to whats_path, alert: "What #{@what.what} is in use by an Item"
		elsif WhatMap.where("what_id = ?", @what.id).count > 0
			redirect_to whats_path, alert: "What #{@what.what} is in use by a WhatMap"
		else
			@what.delete
			redirect_to whats_path, notice: "What #{@what.what} Deleted"
		end
	end

private
	
	def what_params
		params.require(:what).permit(:what, :category_id)
	end

	def require_expenses
		unless has_role(current_user.id, 'expenses')
			redirect_to root_url, alert: "inadequate permissions"
		end
	end

end

app/views/whats/_form.html.erb
<%= form_for(@what) do |form| %>

	<%= form.label :what, class: 'col-md-2' %>
	<%= form.text_field :what, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.label 'Category', class: 'col-md-2' %>
	<%= form.select :category_id, @categories.collect {|category| [category.ctype + '/' + category.category + '/' + category.subcategory + '/' + category.tax, category.id]}, {}, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.submit 'Update What Map', class: 'btn btn-primary col-md-3' %>
<% end %>

app/views/whats/index.html.erb
<h1><%= @title %></h1>

<%= link_to 'New Map', new_what_path %>

<div class='clearfix'><p>&nbsp;</p></div>

<div>
Click on a column header to sort by that column<br/>
<input type="button" value="Show all columns" onclick="javascript:showAllColumns('table_report')"></input>
<span>(Control-click on header to hide a field)</span>
<input type="button" value="Create custom report!" onclick="javascript:createURL('table_report', 'table_urlBox')"></input>
<span id="table_urlBox"></span>
</div>

<table class='table table-bordered table-striped' id='table_report'>

<thead>
<tr>
<th class='table sorttable_alpha' id='WHAT'>What</th>
<th class='table sorttable_alpha' id='TYPE'>Type</th>
<th class='table sorttable_alpha' id='CATEGORY'>Category</th>
<th class='table sorttable_alpha' id='SUBCATEGORY'>Subcategory</th>
<th class='table sorttable_alpha' id='TAX'>Tax</th>
<th class='table sorttable_alpha' id='EDIT'>Edit</th>
<th class='table sorttable_alpha' id='DELETE'>Delete</th>
<th class='table sorttable_alpha' id='REMAP'>Remap</th>
</tr>
</thead>

<tbody>
<% @whats.each do |what| %>
	<tr>
	<td><%= link_to what.what, what_path(id: what.id), method: :get %></td>
	<td><%= @categorymap[what.category_id]['ctype'] %></td>
	<td><%= @categorymap[what.category_id]['category'] %></td>
	<td><%= @categorymap[what.category_id]['subcategory'] %></td>
	<td><%= @categorymap[what.category_id]['tax'] %></td>
	<td><%= link_to 'Edit', edit_what_path(what.id) %></td>
	<td><%= link_to 'Delete', what_path(what.id), method: :delete, data: {confirm: "Delete #{what.what}?"} %></td>
	<td><%= link_to 'Remap', whats_remap_path(id: what.id) %></td>
	</tr>
<% end %>
</tbody>

</table>

<script type="text/javascript">
  var tableFilters = {
    sort_select: true,
    btn_reset: true,
    btn_reset_text: "Clear Filters",
    btn_text: " > ",
    alternate_rows: false,
    flt_row_class: "tableFlt",
    col_width_0: "15", //WHAT
    col_width_1: "5", //TYPE
    col_width_2: "15", //CATEGORY
    col_width_3: "15", //SUBCATEGORY
    col_width_4: "15", //TAX
    col_width_5: "1", //EDIT
    col_width_6: "1", //DELETE
    col_width_7: "1", //REMAP
    display_all_text: "<*>",
  }
  sorttable.makeSortable(document.getElementById('table_report'), 1);
  setFilterGrid('table_report', 1, tableFilters);
  setupSearch('table_report');
</script>

app/views/whats/remap.html.erb
<h1><% @title %></h1>

<%= form_tag whats_remapupdate_path(id: @what.id), :method => :put do %>

	<%= @what.what %>
	<%= select_tag :newid, options_for_select(@whats) %>

	<div class='clearfix'><p>&nbsp;</p></div>

	<%= submit_tag 'Remap', class: 'btn btn-primary col-md-1' %>

<% end %>

app/views/whats/show.html.erb
<h1><%= @title %></h1>

<table>

<thead>
<tr>
<th>Date</th>
<th>+/-</th>
<th>Check</th>
<th>Amount</th>
</tr>
</thead>

<tbody>
<% @items.each do |item| %>
	<tr>
	<th><%= item.date %></th>
	<th><%= item.pm %></th>
	<th><%= item.checkno %></th>
	<th><%= number_with_precision(item.amount, precision: 2) %></th>
	</tr>
<% end %>
</tbody>

</table>