config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'

	resources :sessions
	match '/signout', to: 'sessions#destroy', via: :delete

	resources :users
	match '/users_password_reset', to: 'users#password_reset', via: :get
	match '/users_password_reset_update', to: 'users#password_reset_update', via: :put

	resources :categories
	match '/categoriesbulkinput', to: 'categories#bulkinput', via: :get
	match '/categoriesbulkinputupdate', to: 'categories#bulkinputupdate', via: :get

	resources :whats
	match '/whats_remap', to: 'whats#remap', via: :get
	match '/whats_remapupdate', to: 'whats#remapupdate', via: :put

	resources :what_maps

	resources :accountmaps

	resources :items

	resources :bulkinput

	resources :yearbudget

	resources :runningbudget

	resources :donations

	resources :rentalcosts

	resources :rent

	resources :transfers

	resources :unused

	resources :taxes

	resources :accounts
	match 'account_close', to: 'accounts#close', via: :put

	resources :investments

	resources :investmentbulkinput

	resources :summary_types
	match '/summary_types_showupdate', to: 'summary_types#showupdate', via: :put

	resources :summary

	resources :charts

	resources :rebalance

	resources :rebalance_types
	match '/rebalance_types_showupdate', to: 'rebalance_types#showupdate', via: :put

	match '/admin_roles', to: 'admin#roles', via: :get
	match '/admin_roles_edit', to: 'admin#roles_edit', via: :get
	match '/admin_roles_update', to: 'admin#roles_update', via: :get
	match '/admin_schema', to: 'admin#schema', via: :get
	match '/admin_datacheck', to: 'admin#datacheck', via: :get

end

app/models/summary_type.rb
class SummaryType < ApplicationRecord
	has_many :investment_maps
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController

	before_action :require_signed_in
	before_action :require_investments

	def index
		if params[:fromyear]
			@fromyear = params[:fromyear]
		else
			@fromyear = Time.now.year - 10
		end
		if params[:toyear]
			@toyear = params[:toyear]
		else
			@toyear = Investment.all.order('date DESC').first.date.year
		end
		@title = "Investments Summary"
		@pickyears = []
		Investment.all.pluck(Arel.sql("DISTINCT EXTRACT(year FROM date)")).each do |year|
			@pickyears.push(year.to_i)
		end
		@pickyears = @pickyears.sort
		@years = []
		(@fromyear..@toyear).each do |year|
			@years.push(year.to_i)
		end
		@summaries = Hash.new
		SummaryType.all.order('priority').each do |summary|
			@summaries[summary.id] = Hash.new
			@summaries[summary.id]['name'] = summary.stype
			@summaries[summary.id]['priority'] = summary.priority
			@years.each do |year|
				@summaries[summary.id][year] = 0
			end
			InvestmentMap.where("summary_type_id = ?", summary.id).each do |map|
				t = Hash.new
				Investment.where("account_id = ? AND EXTRACT(year FROM date) >= ? AND EXTRACT(year FROM date) <= ?", map.account_id, @fromyear, @toyear).order('date').each do |investment|
					t[investment.date.year] = investment.value
				end
				@years.each do |year|
					if t[year]
						@summaries[summary.id][year] = @summaries[summary.id][year] + t[year]
					elsif t[year - 1]
						@summaries[summary.id][year] = @summaries[summary.id][year] + t[year - 1]
					end
				end
			end
		end
	end

	def show
		@summarytype = SummaryType.find(params[:id])
		@title = "Account contributions for #{@summarytype.stype}"
		@fromyear = params[:fromyear]
		@toyear = params[:toyear]
		@years = []
		(@fromyear..@toyear).each do |year|
			@years.push(year.to_i)
		end
		@accounts = Hash.new
		InvestmentMap.joins(:account).where("summary_type_id = ?", @summarytype.id).order('account').each do |map|
			@accounts[map.account_id] = Hash.new
			@accounts[map.account_id]['name'] = map.account.account
			@years.each do |year|
				@accounts[map.account_id][year] = 0
			end
			Investment.where("account_id = ? AND EXTRACT(year FROM date) >= ? AND EXTRACT(year FROM date) <= ?", map.account_id, @fromyear, @toyear).order('date').each do |investment|
				@accounts[map.account_id][investment.date.year] = investment.value
			end
			flag = 0
			@years.each do |year|
				if @accounts[map.account_id][year] != 0
					flag = 1
				end
			end
			if flag == 0
				@accounts.delete(map.account_id)
			end
		end
	end

private

	def require_investments
		unless has_role(current_user.id, 'investments')
			redirect_to root_url, alert: "inadequate permissions"
		end
	end

end

app/views/summary/index.html.erb
<h1><%= @title %></h1>

<div class='dropdown'>
	<a href='#' data-toggle='dropdown' class='dropdown-toggle'>From Year <b class='caret'></b></a>
	<ul class='dropdown-menu'>
		<% @pickyears.each do |year| %>
			<li><%= link_to year, summary_index_path(fromyear: year, toyear: @toyear) %></li>
		<% end %>
	</ul>
</div>

<div class='dropdown'>
	<a href='#' data-toggle='dropdown' class='dropdown-toggle'>To Year <b class='caret'></b></a>
	<ul class='dropdown-menu'>
		<% @pickyears.each do |year| %>
			<li><%= link_to year, summary_index_path(fromyear: @fromyear, toyear:year) %></li>
		<% end %>
	</ul>
</div>

<div class='clearfix'><p>&nbsp;</p></div>

<table>

<thead>
<tr>
<th>Summary</th>
<% @years.each do |year| %>
	<th><%= year %></th>
<% end %>
</tr>
</thead>

<tbody>
<% lastpriority = 0 %>
<% @summaries.each do |id, summary| %>
	<% if lastpriority + 1 != summary['priority'] %>
		<tr><td>&nbsp;</td></tr>
	<% end %>
	<% lastpriority = summary['priority'] %>
	<tr>
	<td><%= link_to summary['name'], summary_path(id: id, fromyear: @fromyear, toyear: @toyear) %></td>
	<% @years.each do |year| %>
		<td><%= link_to number_with_precision(summary[year], precision: 2), summary_path(id: id, fromyear: year, toyear: year) %></td>
	<% end %>
	</tr>
<% end %>
</tbody>

</table>

<div class='clearfix'><p>&nbsp;</p></div>

<p><%= link_to 'Charts', charts_path(fromyear: @fromyear, toyear: @toyear), class: 'btn btn-primary col-md-1', target: "_blank" %></p>

app/views/summary/show.html.erb
<h1><%= @title %></h1>

<table>

<thead>
<tr>
<th>Account</th>
<% @years.each do |year| %>
	<th><%= year %></th>
<% end %>
</tr>
</thead>

<tbody>
<% @accounts.each do |id, values| %>
	<tr>
	<td><%= values['name'] %></td>
	<% @years.each do |year| %>
		<th><%= number_with_precision(values[year], precision: 2) %></th>
	<% end %>
	</tr>
<% end %>
</tbody>

</table>