config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'

	resources :sessions
	match '/signout', to: 'sessions#destroy', via: :delete

	resources :users
	match '/users_password_reset', to: 'users#password_reset', via: :get
	match '/users_password_reset_update', to: 'users#password_reset_update', via: :put

	resources :categories
	match '/categoriesbulkinput', to: 'categories#bulkinput', via: :get
	match '/categoriesbulkinputupdate', to: 'categories#bulkinputupdate', via: :get

	resources :whats
	match '/whats_remap', to: 'whats#remap', via: :get
	match '/whats_remapupdate', to: 'whats#remapupdate', via: :put

	resources :what_maps

	resources :accountmaps

	resources :items

	resources :bulkinput

	resources :yearbudget

	resources :runningbudget

	resources :donations

	resources :rentalcosts

	resources :rent

	resources :transfers

	resources :unused

	resources :taxes

	resources :accounts
	match 'account_close', to: 'accounts#close', via: :put

	resources :investments

	resources :investmentbulkinput

	resources :summary_types
	match '/summary_types_showupdate', to: 'summary_types#showupdate', via: :put

	resources :summary

	resources :charts

	resources :rebalance

	resources :rebalance_types
	match '/rebalance_types_showupdate', to: 'rebalance_types#showupdate', via: :put

	match '/admin_roles', to: 'admin#roles', via: :get
	match '/admin_roles_edit', to: 'admin#roles_edit', via: :get
	match '/admin_roles_update', to: 'admin#roles_update', via: :get
	match '/admin_schema', to: 'admin#schema', via: :get
	match '/admin_datacheck', to: 'admin#datacheck', via: :get

end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :whats

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_signed_in
	before_action :require_expenses

	def index
		@title = 'Categories'
		@categories = Category.all.order('ctype, category, subcategory')
	end

	def new
		@title = 'New Category'
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path, notice: 'Category Added'
		else
			redirect_to categories_path, alert: 'Failed to create Category'
		end
	end

	def edit
		@title = 'Edit Category'
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to categories_path, notice: 'Category Updated'
		else
			redirect_to categories_path, alert: 'Failed to update Category'
		end
	end

	def show
		@category = Category.find(params[:id])
		@title = "What maps to #{@category.ctype}/#{@category.category}/#{@category.subcategory}"
		@whats = What.where("category_id = ?", @category.id).order('what')
	end

	def destroy
		@category = Category.find(params[:id])
		if What.where("category_id = ?", @category.id).count > 0
			redirect_to categories_path, alert: "Category #{@category.ctype}/#{@category.category}/#{@category.subcategory}/#{@category.tax} is in use by a What"
		else
			@category.delete
			redirect_to categories_path, notice: "Category #{@category.ctype}/#{@category.category}/#{@category.subcategory}/#{@category.tax} Deleted"
		end
	end

	def bulkinput
		@title = 'Bulk Input of Categories'
		@input = ''
	end

	def bulkinputupdate
		@title = 'Bulk Input of Categories'
		@input = params[:input]
		@errors = []
		lines = @input.split("\n")
		lines.each do |line|
			# parse line
			fields = line.split("\t")
			if fields[2]
				ctype = fields[0].gsub(/^\s*/, '').gsub(/\s*$/, '')
				category = fields[1].gsub(/^\s*/, '').gsub(/\s*$/, '')
				subcategory = fields[2].gsub(/^\s*/, '').gsub(/\s*$/, '')
				if fields[3]
					tax = fields[3].gsub(/^\s*/, '').gsub(/\s*$/, '')
				else
					tax = ''
				end
				db = Category.where("ctype = ? AND category = ? AND subcategory = ? AND tax = ?", ctype, category, subcategory, tax)
				if db.count > 0
					@errors.push("DUP: #{line}")
				else
					newcategory = Category.new
					newcategory.ctype = ctype
					newcategory.category = category
					newcategory.subcategory = subcategory
					newcategory.tax = tax
					newcategory.save
					@errors.push("ADDED: #{line}")
				end
			else
				@errors.push("BAD LINE: #{line}")
			end
		end
		render action: :bulkinput
	end

private
	
	def category_params
		params.require(:category).permit(:ctype, :category, :subcategory, :tax)
	end

	def require_expenses
		unless has_role(current_user.id, 'expenses')
			redirect_to root_url, alert: "inadequate permissions"
		end
	end

end

app/views/categories/_form.html.erb
<%= form_for(@category) do |form| %>

	<%= form.label 'Type', class: 'col-md-2' %>
	<%= form.text_field :ctype, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.label :category, class: 'col-md-2' %>
	<%= form.text_field :category, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.label :subcategory, class: 'col-md-2' %>
	<%= form.text_field :subcategory, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.label :tax, class: 'col-md-2' %>
	<%= form.text_field :tax, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.submit 'Update Category', class: 'btn btn-primary col-md-3' %>
<% end %>

app/views/categories/bulkinput.html.erb
<h1><%= @title %></h1>

<% if @errors && @errors.count > 0 %>
Notes:
<ul>
<% @errors.each do |error| %>
	<li><%= error %></li>
<% end %>
</ul>
<% end %>

Text area is a series of lines with the following tab separated columns:
<ul>
<li>type</li>
<li>category</li>
<li>subcategory</li>
<li>tax</li>
</ul>

<%= form_tag categoriesbulkinputupdate_path, method: :get do %>

<%= text_area_tag :input, @input %>

<div class='clearfix'><p>&nbsp;</p></div>

<%= submit_tag 'Submit', class: 'btn btn-primary col_md_1' %>

<% end %>

app/views/categories/index.html.erb
<h1><%= @title %></h1>

<%= link_to 'New Category', new_category_path, class: 'btn btn-primary col-md-1' %>

<div class='clearfix'><p>&nbsp;</p></div>
<div class='clearfix'><p>&nbsp;</p></div>

<div>
Click on a column header to sort by that column<br/>
<input type="button" value="Show all columns" onclick="javascript:showAllColumns('table_report')"></input>
<span>(Control-click on header to hide a field)</span>
<input type="button" value="Create custom report!" onclick="javascript:createURL('table_report', 'table_urlBox')"></input>
<span id="table_urlBox"></span>
</div>

<table class='table table-bordered table-striped' id='table_report'>

<thead>
<tr>
<th class='table sorttable_alpha' id='TYPE'>Type</th>
<th class='table sorttable_alpha' id='CATEGORY'>Category</th>
<th class='table sorttable_alpha' id='SUBCATEGORY'>Subcategory</th>
<th class='table sorttable_alpha' id='TAX'>Tax</th>
<th class='table sorttable_alpha' id='EDIT'>Edit</th>
<th class='table sorttable_alpha' id='DELETE'>Delete</th>
<th class='table sorttable_alpha' id='DETAILS'>Details</th>
</tr>
</thead>

<tbody>
<% @categories.each do |category| %>
	<tr>
	<td><%= category.ctype %></td>
	<td><%= category.category %></td>
	<td><%= category.subcategory %></td>
	<td><%= category.tax %></td>
	<td><%= link_to 'Edit', edit_category_path(category.id) %></td>
	<td><%= link_to 'Delete', category_path(category.id), method: :delete, data: {confirm: "Delete #{category.ctype}/#{category.category}/#{category.subcategory}/#{category.tax}?"} %></td>
	<td><%= link_to 'Details', category_path(category.id) %></td>
	</tr>
<% end %>
</tbody>

</table>

<div class='clearfix'><p>&nbsp;</p></div>

<%= link_to 'Bulk Input', categoriesbulkinput_path, class: 'btn btn-primary col-md-1' %></td>

<script type="text/javascript">
  var tableFilters = {
    sort_select: true,
    btn_reset: true,
    btn_reset_text: "Clear Filters",
    btn_text: " > ",
    alternate_rows: false,
    flt_row_class: "tableFlt",
    col_width_0: "5", //TYPE
    col_width_1: "15", //CATEGORY
    col_width_2: "15", //SUBCATEGORY
    col_width_3: "15", //TAX
    col_width_4: "1", //EDIT
    col_width_5: "1", //DELETE
    col_width_6: "1", //DELETE
    display_all_text: "<*>",
  }
  sorttable.makeSortable(document.getElementById('table_report'), 1);
  setFilterGrid('table_report', 1, tableFilters);
  setupSearch('table_report');
</script>

app/views/categories/show.html.erb
<h1><%= @title %></h1>

<table>

<thead>
<tr>
<th>What</th>
</tr>
</thead>

<tbody>
<% @whats.each do |what| %>
	<tr>
	<td><%= link_to what.what, what_path(id: what.id), method: :get %></td>
	</tr>
<% end %>
</tbody>

</table>