config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'

	resources :sessions
	match '/signout', to: 'sessions#destroy', via: :delete

	resources :users
	match '/users_password_reset', to: 'users#password_reset', via: :get
	match '/users_password_reset_update', to: 'users#password_reset_update', via: :put

	resources :categories
	match '/categoriesbulkinput', to: 'categories#bulkinput', via: :get
	match '/categoriesbulkinputupdate', to: 'categories#bulkinputupdate', via: :get

	resources :whats
	match '/whats_remap', to: 'whats#remap', via: :get
	match '/whats_remapupdate', to: 'whats#remapupdate', via: :put

	resources :what_maps

	resources :accountmaps

	resources :items

	resources :bulkinput

	resources :yearbudget

	resources :runningbudget

	resources :donations

	resources :rentalcosts

	resources :rent

	resources :transfers

	resources :unused

	resources :taxes

	resources :accounts
	match 'account_close', to: 'accounts#close', via: :put

	resources :investments

	resources :investmentbulkinput

	resources :summary_types
	match '/summary_types_showupdate', to: 'summary_types#showupdate', via: :put

	resources :summary

	resources :charts

	resources :rebalance

	resources :rebalance_types
	match '/rebalance_types_showupdate', to: 'rebalance_types#showupdate', via: :put

	match '/admin_roles', to: 'admin#roles', via: :get
	match '/admin_roles_edit', to: 'admin#roles_edit', via: :get
	match '/admin_roles_update', to: 'admin#roles_update', via: :get
	match '/admin_schema', to: 'admin#schema', via: :get
	match '/admin_datacheck', to: 'admin#datacheck', via: :get

end

app/models/accountmap.rb
class Accountmap < ApplicationRecord
end

app/controllers/accountmaps_controller.rb
class AccountmapsController < ApplicationController

	before_action :require_signed_in
	before_action :require_expenses

	def index
		@title = 'Account Number to Category Type'
		@accountmaps = Accountmap.all.order('account')
	end

	def new
		@title = 'New Account Map'
		@accountmap = Accountmap.new
	end

	def create
		@accountmap = Accountmap.new(accountmap_params)
		if @accountmap.save
			redirect_to accountmaps_path, notice: 'Account Map Added'
		else
			redirect_to accountmaps_path, alert: 'Failed to create Account Map'
		end
	end

	def edit
		@title = 'Edit Account Map'
		@accountmap = Accountmap.find(params[:id])
	end

	def update
		@accountmap = Accountmap.find(params[:id])
		if @accountmap.update(accountmap_params)
			redirect_to accountmaps_path, notice: 'Account map Updated'
		else
			redirect_to accountmaps_path, alert: 'Failed to create Account map'
		end
	end

	def destroy
		@accountmap = Accountmap.find(params[:id])
		@accountmap.delete
		redirect_to accountmaps_path, notice: "Accountmap #{@accountmap.account} Deleted"
	end

private
	
	def accountmap_params
		params.require(:accountmap).permit(:account, :ctype)
	end

	def require_expenses
		unless has_role(current_user.id, 'expenses')
			redirect_to root_url, alert: "inadequate permissions"
		end
	end

end

app/views/accountmaps/_form.html.erb
<%= form_for(@accountmap) do |form| %>

	<%= form.label :account, class: 'col-md-2' %>
	<%= form.text_field :account, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.label :ctype, class: 'col-md-2' %>
	<%= form.text_field :ctype, class: 'col-md-10' %>

	<div class='clearfix'></div>

	<%= form.submit 'Update Account Map', class: 'btn btn-primary col-md-3' %>
<% end %>

app/views/accountmaps/index.html.erb
<h1><%= @title %></h1>

<%= link_to 'New Map', new_accountmap_path %>

<div class='clearfix'><p>&nbsp;</p></div>

<table table-bordered>

<thead>
<tr>
<th>Account Number</th>
<th>Category Type</th>
<th>Edit</th>
<th>Delete</th>
</tr>
</thead>

<tbody>
<% @accountmaps.each do |accountmap| %>
	<tr>
	<td><%= accountmap.account %></td>
	<td><%= accountmap.ctype %></td>
	<td><%= link_to 'Edit', edit_accountmap_path(accountmap.id) %></td>
	<td><%= link_to 'Delete', accountmap_path(accountmap.id), method: :delete, data: {confirm: "Delete #{accountmap.account}?"} %></td>
	</tr>
<% end %>
</tbody>

</table>